
CREATE DATABASE music_library;

CREATE TABLE ARTISTS (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE ALBUMS (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	artist_id INT REFERENCES ARTISTS(id),
	release_date DATE,
	cover_image BYTEA
);

CREATE TABLE SONGS (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	artist VARCHAR(255) NOT NULL,
	album VARCHAR(255),
	release_date DATE,
	genre VARCHAR(100),
	data BYTEA NOT NULL
);

CREATE TABLE PLAYLISTS (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT
);

CREATE TABLE PLAYLIST_SONGS (
	playlist_id INT REFERENCES PLAYLISTS(id),
	song_id INT REFERENCES SONGS(id),
	PRIMARY KEY (playlist_id, song_id)
);